spring:
  application:
    name: pingpongback
  datasource:
    url: ${DB_URL}
    username: postgres.hedirzdlhezaskjoridq   # <--- DAS HIER IST NEU!
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update